:bug: Fix "xdata" bug
* When plotting any convoluted images, Octave raised the following error:
```matlab
error: 'xdata' undefined near line 205 column 49
error: called from
    image>__img__ at line 205 column 5
    image at line 125 column 10
    imagesc at line 101 column 12
    imshow at line 208 column 10
    tp3 at line 39 column 1
```
The problem came from the fact that the given image was empty, because of the chain of function I created. Octave might not be able the chain functions.